INSERT INTO scam_types (id, name, description) VALUES (1, 'Charity fund scam', '');
INSERT INTO scam_types (id, name, description) VALUES (2, 'Employment Scam', '');
INSERT INTO scam_types (id, name, description) VALUES (3, 'Employment Scam ', '');
INSERT INTO scam_types (id, name, description) VALUES (4, 'Employment scam ', '');
INSERT INTO scam_types (id, name, description) VALUES (5, 'Fake loan scam', '');
INSERT INTO scam_types (id, name, description) VALUES (6, 'Fishing scam', '');
INSERT INTO scam_types (id, name, description) VALUES (7, 'Forex scam', '');
INSERT INTO scam_types (id, name, description) VALUES (8, 'Investment Scam', '');
INSERT INTO scam_types (id, name, description) VALUES (9, 'Investment fraud and Phishing', '');
INSERT INTO scam_types (id, name, description) VALUES (10, 'Investment scam', '');
INSERT INTO scam_types (id, name, description) VALUES (11, 'Investment scam ', '');
INSERT INTO scam_types (id, name, description) VALUES (12, 'Investment scams', '');
INSERT INTO scam_types (id, name, description) VALUES (13, 'Job Scam ', '');
INSERT INTO scam_types (id, name, description) VALUES (14, 'Loan Scam', '');
INSERT INTO scam_types (id, name, description) VALUES (15, 'Loan scam', '');
INSERT INTO scam_types (id, name, description) VALUES (16, 'Loan scam (Phishing)', '');
INSERT INTO scam_types (id, name, description) VALUES (17, 'Loan/Financial Scam', '');
INSERT INTO scam_types (id, name, description) VALUES (18, 'Love Scam', '');
INSERT INTO scam_types (id, name, description) VALUES (19, 'Love scam', '');
INSERT INTO scam_types (id, name, description) VALUES (20, 'Love scam or Charity fund scam', '');
INSERT INTO scam_types (id, name, description) VALUES (21, 'Love scams, Employment scam', '');
INSERT INTO scam_types (id, name, description) VALUES (22, 'Love/Relationship Scam', '');
INSERT INTO scam_types (id, name, description) VALUES (23, 'Online Employment Scam', '');
INSERT INTO scam_types (id, name, description) VALUES (24, 'Online Employment Scam ', '');
INSERT INTO scam_types (id, name, description) VALUES (25, 'Online Fraud', '');
INSERT INTO scam_types (id, name, description) VALUES (26, 'Online Scam', '');
INSERT INTO scam_types (id, name, description) VALUES (27, 'Online love scam', '');
INSERT INTO scam_types (id, name, description) VALUES (28, 'Online scam', '');
INSERT INTO scam_types (id, name, description) VALUES (29, 'Other', '');
INSERT INTO scam_types (id, name, description) VALUES (30, 'Parcel scam', '');
INSERT INTO scam_types (id, name, description) VALUES (31, 'Phishing', '');
INSERT INTO scam_types (id, name, description) VALUES (32, 'Phishing ', '');
INSERT INTO scam_types (id, name, description) VALUES (33, 'Share investment scam', '');
INSERT INTO scam_types (id, name, description) VALUES (34, 'iPhishing', '');
INSERT INTO scam_types (id, name, description) VALUES (35, 'love and Employment Scam', '');
INSERT INTO scam_types (id, name, description) VALUES (36, 'online scam', '');
